slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: mapping 
    odom_frame: odom
    map_frame: map
    base_frame: base_link

    scan_topic: /scan
    odom_topic: /odom
    imu_topic: /imu_plugin/out

    minimum_time_interval: 0.5
    map_update_interval: 2.0
    resolution: 0.05
    max_laser_range: 10.0
